# Generated by Django 4.1.5 on 2023-01-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatialdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipcode',
            old_name='poly',
            new_name='home',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='code',
        ),
        migrations.AddField(
            model_name='zipcode',
            name='address',
            field=models.CharField(default=(1, 3), max_length=255),
            preserve_default=False,
        ),
    ]
